config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root('pages#index')
  # get 'list', to: 'pages#list'
  resources :keys, only: [:index, :destroy, :create] do
    collection do
      post 'random'
    end
    member do
      put 'keys_called_at'
      put 'keys_revived_at'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/delayed_job.rb
class DelayedJob < ApplicationRecord
end

app/models/key.rb
class Key < ApplicationRecord
    validates :key, uniqueness: true
    scope :random_key, -> { order(Arel.sql("RANDOM()")).first }
    def update_key_called_at
        update(used: false, called_at: Time.now)
    end
    def update_key_revived_at
        update(revived_at: Time.now)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/keys_controller.rb
class KeysController < ApplicationController

    before_action :set_key, only: [:keys_called_at, :keys_revived_at, :destroy]

    def create
        Key.create(key: rand(100_000..999_999), called_at: Time.now, revived_at: Time.now)
        redirect_to keys_path
        flash[:notice]="Created a new key"
    end

    def index
        @keys=Key.paginate(page: params[:page], per_page: 15)
    end

    def random
        @keys=Key.where(used: false)
        if @keys.empty?
            render plain: "Keys not found"
            redirect_to keys_path
            flash[:alert]="Key not found"
        else
            @random_key = @keys.random_key
            @random_key.transaction do
              @random_key.update(used: true, called_at: Time.now)
              UnblockKeyJob.delay(run_at: 1.minute.from_now).perform_later(@random_key.id)
            end
            redirect_to keys_path
            flash[:notice]="The key assigned to you is #{@random_key.key}"
        end
    end

    def keys_called_at
        @key.update_key_called_at
        redirect_to keys_path
        flash[:notice]="Unblocked key #{@key.key}"
    end

    def keys_revived_at
        @key.update_key_revived_at
        redirect_to keys_path
        flash[:notice]="Revived key #{@key.key}"
    end

    def destroy
        @key.destroy
        redirect_to keys_path
        flash[:alert]="Key deleted"
    end

    private
    def set_key
        @key = Key.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def format_time_in_kolkata(time)
        time.in_time_zone('Asia/Kolkata').strftime('%Y-%m-%d %H:%M:%S')
    end
end

app/views/keys/index.html.erb
<%=link_to "Generate new key", keys_path, class: "btn btn-success", method: :post%>
<%=link_to "Assign a key", random_keys_path, class: "btn btn-success", method: :post%>

<div class="flickr_pagination">
    <%= will_paginate @keys, :container => false %>
</div>
<table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Key</th>
      <th scope="col">Used</th>
      <th scope="col">Created At</th>
      <th scope="col">Updated At</th>
      <th scope="col">Called At</th>
      <th scope="col">Revived At</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    
    <% @keys.each do |key| %>
        <tr>
            <td><%= key.id %></td>
            <td><%= key.key %></td>
            <td><%= key.used %></td>
            <td><%= format_time_in_kolkata(key.created_at) %></td>
            <td><%= format_time_in_kolkata(key.updated_at) %></td>
            <td><%= format_time_in_kolkata(key.called_at) %></td>
            <td><%= format_time_in_kolkata(key.revived_at) %></td>
            <td>
                <%=link_to "Delete", key_path(key), class: "mr-4", method: :delete, data: {confirm: "Are you sure?"}%>
                <%=link_to "Keep alive", keys_revived_at_key_path(key), class: "mr-4", method: :put%>
                <% if key.used %>
                    <%=link_to "Unblock", keys_called_at_key_path(key), class: "mr-4", method: :put%>
                <% end %>
            </td>
        </tr>
    <%end%>

  </tbody>
</table>
<div class="flickr_pagination">
    <%= will_paginate @keys, :container => false %>
</div>

app/views/keys/random.html.erb
The key assigned to you is <%= @random_key.key %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KeysAssignment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
        <%= msg %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>